name: hydrus
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab
  - black
  - nbqa
  - numpy
  - pillow
  - pandas
  - openpyxl
  - feather-format
  - scipy
  - matplotlib
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - seaborn
  - cartopy
  - geopandas
  - geoplot
  - pyepsg
  - plotly
  - spotpy
  - deap
  - platypus-opt
  - scikit-learn
  - python-graphviz
  - numba
  - pytest
  - ipytest
  - twine
