name: hydrus
channels:
  - conda-forge
  - plotly
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - feather-format
  - xlrd
  - xarray
  - bottleneck
  - netcdf4
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - cartopy
  - geopandas
  - geoplot
  - plotly
  - plotly-geo
  - bokeh
  - platypus-opt
  - pytorch
  - torchvision
  - tensorboard
  - shap
  - optuna
  - aiohttp
  - cloudpickle
  - distributed
  - joblib
  - pandas-datareader
  - pytables
  - snakeviz
  - ujson
  - gcsfs
  - ipywidgets
  - numba
  - h5py
  - scikit-image
  - dask
  - python-graphviz
  - s3fs
  - loky
  - pip
  - pip:
    - clearml
    - clearml-agent