name: hydrus
channels:
  - conda-forge
  - plotly
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - flask
  - numpy
  - pandas
  - feather-format
  - xlrd
  - xarray
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - cartopy
  - geopandas
  - geoplot
  - plotly
  - plotly-geo
  - bokeh
  - bayesian-optimization
  - platypus-opt
  - pytorch
  - torchvision
  - skorch
  - aiohttp
  - cloudpickle
  - distributed
  - joblib
  - pandas-datareader
  - pytables
  - snakeviz
  - ujson
  - gcsfs
  - ipywidgets
  - numba
  - h5py
  - scikit-image
  - dask
  - python-graphviz
  - s3fs
  - loky
  - findspark