name: hydrus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - numpy
  - pandas
  - openpyxl
  - feather-format
  - scipy
  - matplotlib
  - xarray
  - netCDF4
  - dask
  - seaborn
  - cartopy
  - geopandas
  - geoplot
  - plotly
