name: tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - xarray
  - rioxarray
  - openpyxl
  - pip
  - netCDF4
  - pytorch
  - torchvision
  - pyarrow
  - graphviz
  - pip:
    - jupyter-book
    - matplotlib
    - ghp-import
    - torchviz
    - black
    - wis-downloader
    - hydrodataset